const ContactsTypes = {
    FETCH_CONTACTS_START: 'FETCH_CONTACTS_START',
    SET_CONTACTS_SUCCESS: 'SET_CONTACTS_SUCCESS',
    SET_CONTACTS_FAILURE: 'SET_CONTACTS_FAILURE',
}

export default ContactsTypes;