const ContactsTypes = {
    FETCH_CONTACTS_START: 'FETCH_CONTACTS_START',
    SET_CONTACTS_SUCCESS: 'SET_CONTACTS_SUCCESS',
    SET_CONTACTS_FAILURE: 'SET_CONTACTS_FAILURE',
    FILTER_BY_DATA: 'FILTER_BY_DATA',
    ADD_FILTER: 'ADD_FILTER',
    DELETE_FILTER: 'DELETE_FILTER',
    DELETE_ALL_FILTERS: 'DELETE_ALL_FILTERS',

}

export default ContactsTypes;